service: chatbot-ml-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: eu-central-1
  memorySize: 512
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: arn:aws:s3:::chatbot-ml-predictor/*
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  # trainModel:
  #   handler: train_handler.lambda_handler
  #   events:
  #     - s3:
  #         bucket: your-chatbot-bucket-name
  #         event: s3:ObjectCreated:*
  #         rules:
  #           - prefix: dataset/
  #           - suffix: .csv
  #         existing: true

  predictAnswer:
    handler: predict.lambda_handler
    events:
      - httpApi:
          path: /predict
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
