name: Deploy Lambda Functions

on:
  push:
    branches: [main]

jobs:
  deploy--predict-function-to-aws-lambda:
    name: Deploy Predict Function to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies into package/
        working-directory: ./lambda/predict
        run: |
          mkdir -p package
          pip install -r requirements.txt -t package

      - name: Copy handler to root
        working-directory: ./lambda/predict
        run: |
          cp lambda_function.py package/

      - name: Create deployment package
        working-directory: ./lambda/predict
        run: |
         cd package
         zip -r ../lambda_deploy_package.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS Lambda
        working-directory: ./lambda/predict
        run: |
         aws lambda update-function-code \
          --function-name predictFunction \
          --zip-file fileb://lambda_deploy_package.zip


